spring.application.name=backend

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:taskmanagement}
spring.datasource.username=${DB_USER:taskmanagement}
spring.datasource.password=${DB_PASSWORD:taskmanagement}
spring.jpa.hibernate.ddl-auto=update
